name: "AI Code Reviewer for Pull Requests"
description: "Review, summarize and auto-fix pull requests with AI"
author: "Presubmit.ai"
branding:
  icon: "check-square"
  color: "black"

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  style_guide_rules:
    required: false
    description: 'Custom style guide rules that will be enforced during review by generating critical comments'
    default: ''